"""Create initial tables

Revision ID: 7e7ed367cffc
Revises: 
Create Date: 2025-12-10 20:55:59.737784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7ed367cffc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_location',
    sa.Column('car_location_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('car_location_id')
    )
    op.create_index(op.f('ix_car_location_car_location_id'), 'car_location', ['car_location_id'], unique=False)
    op.create_table('car_model',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'ELECTRIC', 'HYBRID', name='fueltype'), nullable=False),
    sa.Column('base_price', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('base_price > 0', name='check_base_price_positive'),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index(op.f('ix_car_model_model_id'), 'car_model', ['model_id'], unique=False)
    op.create_index(op.f('ix_car_model_model_name'), 'car_model', ['model_name'], unique=True)
    op.create_table('driver_license',
    sa.Column('driver_license_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.CHAR(length=10), nullable=False),
    sa.Column('license_type', sa.Enum('M', 'A', 'A1', 'B', 'B1', 'BE', 'C1', 'D1', name='licensetype'), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('driver_license_id')
    )
    op.create_index(op.f('ix_driver_license_driver_license_id'), 'driver_license', ['driver_license_id'], unique=False)
    op.create_index(op.f('ix_driver_license_license_number'), 'driver_license', ['license_number'], unique=True)
    op.create_table('car',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'MAINTENANCE', 'UNAVAILABLE', name='carstatus'), nullable=False),
    sa.ForeignKeyConstraint(['location'], ['car_location.car_location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['car_model.model_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('car_id')
    )
    op.create_index(op.f('ix_car_car_id'), 'car', ['car_id'], unique=False)
    op.create_index(op.f('ix_car_license_plate'), 'car', ['license_plate'], unique=True)
    op.create_index(op.f('ix_car_location'), 'car', ['location'], unique=False)
    op.create_index(op.f('ix_car_model_id'), 'car', ['model_id'], unique=False)
    op.create_index(op.f('ix_car_status'), 'car', ['status'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('driver_license_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=32), nullable=False),
    sa.Column('lastname', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['driver_license_id'], ['driver_license.driver_license_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_driver_license_id'), 'user', ['driver_license_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('booking',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.car_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_booking_book_id'), 'booking', ['book_id'], unique=False)
    op.create_index(op.f('ix_booking_car_id'), 'booking', ['car_id'], unique=False)
    op.create_index(op.f('ix_booking_status'), 'booking', ['status'], unique=False)
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    op.create_table('trip',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('start_location', sa.Integer(), nullable=True),
    sa.Column('end_location', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.CheckConstraint('price >= 0', name='check_price_non_negative'),
    sa.ForeignKeyConstraint(['book_id'], ['booking.book_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['end_location'], ['car_location.car_location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['start_location'], ['car_location.car_location_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_trip_book_id'), 'trip', ['book_id'], unique=False)
    op.create_index(op.f('ix_trip_end_location'), 'trip', ['end_location'], unique=False)
    op.create_index(op.f('ix_trip_start_location'), 'trip', ['start_location'], unique=False)
    op.create_index(op.f('ix_trip_start_time'), 'trip', ['start_time'], unique=False)
    op.create_index(op.f('ix_trip_trip_id'), 'trip', ['trip_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', name='paymenttype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', name='status'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.trip_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_index(op.f('ix_payment_trip_id'), 'payment', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_trip_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_trip_trip_id'), table_name='trip')
    op.drop_index(op.f('ix_trip_start_time'), table_name='trip')
    op.drop_index(op.f('ix_trip_start_location'), table_name='trip')
    op.drop_index(op.f('ix_trip_end_location'), table_name='trip')
    op.drop_index(op.f('ix_trip_book_id'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_status'), table_name='booking')
    op.drop_index(op.f('ix_booking_car_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_book_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_driver_license_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_car_status'), table_name='car')
    op.drop_index(op.f('ix_car_model_id'), table_name='car')
    op.drop_index(op.f('ix_car_location'), table_name='car')
    op.drop_index(op.f('ix_car_license_plate'), table_name='car')
    op.drop_index(op.f('ix_car_car_id'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_driver_license_license_number'), table_name='driver_license')
    op.drop_index(op.f('ix_driver_license_driver_license_id'), table_name='driver_license')
    op.drop_table('driver_license')
    op.drop_index(op.f('ix_car_model_model_name'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_model_id'), table_name='car_model')
    op.drop_table('car_model')
    op.drop_index(op.f('ix_car_location_car_location_id'), table_name='car_location')
    op.drop_table('car_location')
    # ### end Alembic commands ###
