"""Added date columns to bookings

Revision ID: a389956bf545
Revises: fc414d616f5f
Create Date: 2025-12-17 11:36:18.394014

"""
from datetime import date
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a389956bf545'
down_revision: Union[str, Sequence[str], None] = 'fc414d616f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.add_column('booking', sa.Column('end_date', sa.Date(),server_default=sa.text('CURRENT_DATE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'end_date')
    op.drop_column('booking', 'start_date')
    # ### end Alembic commands ###
