"""remove unneeded indexes

Revision ID: f9fd9c24f4bd
Revises: 7376dd384a23
Create Date: 2025-12-18 03:44:00.070862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fd9c24f4bd'
down_revision: Union[str, Sequence[str], None] = '7376dd384a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_booking_id'), table_name='booking')
    op.drop_index(op.f('ix_car_car_id'), table_name='car')
    op.drop_index(op.f('ix_car_license_plate'), table_name='car')
    op.create_unique_constraint(None, 'car', ['license_plate'])
    op.drop_index(op.f('ix_car_location_car_location_id'), table_name='car_location')
    op.drop_index(op.f('ix_car_model_model_id'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_model_name'), table_name='car_model')
    op.create_unique_constraint(None, 'car_model', ['model_name'])
    op.drop_index(op.f('ix_driver_license_driver_license_id'), table_name='driver_license')
    op.drop_index(op.f('ix_driver_license_license_number'), table_name='driver_license')
    op.create_unique_constraint(None, 'driver_license', ['license_number'])
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_trip_trip_id'), table_name='trip')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_trip_trip_id'), 'trip', ['trip_id'], unique=False)
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=False)
    op.drop_constraint(None, 'driver_license', type_='unique')
    op.create_index(op.f('ix_driver_license_license_number'), 'driver_license', ['license_number'], unique=True)
    op.create_index(op.f('ix_driver_license_driver_license_id'), 'driver_license', ['driver_license_id'], unique=False)
    op.drop_constraint(None, 'car_model', type_='unique')
    op.create_index(op.f('ix_car_model_model_name'), 'car_model', ['model_name'], unique=True)
    op.create_index(op.f('ix_car_model_model_id'), 'car_model', ['model_id'], unique=False)
    op.create_index(op.f('ix_car_location_car_location_id'), 'car_location', ['car_location_id'], unique=False)
    op.drop_constraint(None, 'car', type_='unique')
    op.create_index(op.f('ix_car_license_plate'), 'car', ['license_plate'], unique=True)
    op.create_index(op.f('ix_car_car_id'), 'car', ['car_id'], unique=False)
    op.create_index(op.f('ix_booking_booking_id'), 'booking', ['booking_id'], unique=False)
    # ### end Alembic commands ###
